site_name: Wyre
repo_url: http://github.com/from-nibly/wyre
site_author: from-nibly
docs_dir: ./

pages:
- ['./index.md', 'Getting Started', 'Home']
- ['./gettingStarted/callbacksPromises.md', 'Getting Started', 'Callbacks And Promises']
- ['./classes/client.md', 'Classes', 'Client']
- ['./classes/connection.md', 'Classes', 'Connection']
- ['./classes/context.md', 'Classes', 'Context']
- ['./classes/server.md', 'Classes', 'Server']
- ['./configuration/eventListening.md', 'Configuration', 'Event Listening']
- ['./configuration/use.md', 'Configuration', 'Use']